export const words = [
  "agile", "apple", "anger", "angle", "adult", "admit", "arena", "asset", "aside", "attic",
  "badge", "bison", "brave", "basic", "block", "blade", "boost", "booth", "bliss", "bluff",
  "candy", "crate", "cover", "charm", "clear", "class", "climb", "crown", "creep", "chill",
  "dance", "drive", "drain", "dread", "draft", "dream", "drill", "dizzy", "diner", "depth",
  "eager", "evoke", "entry", "equal", "elder", "exist", "enjoy", "essay", "event", "exile",
  "faint", "flame", "ferry", "frame", "flush", "floor", "focus", "fault", "flare", "froth",
  "ghost", "great", "grind", "globe", "guard", "grant", "grove", "grasp", "glory", "glide",
  "haste", "hover", "happy", "heart", "hinge", "honor", "humor", "haunt", "habit", "haste",
  "inbox", "ideal", "image", "index", "infer", "input", "ivory", "issue", "imply", "icy",
  "jolly", "joker", "joint", "judge", "jewel", "jiffy", "jumbo", "juice", "jaunty", "jumpy",
  "karma", "kneel", "knock", "knife", "kinky", "kayak", "known", "kitty", "kudos", "kinky",
  "lucky", "lapse", "lemon", "light", "lover", "laugh", "lurch", "lobby", "layer", "large",
  "magic", "maple", "march", "major", "model", "mellow", "mercy", "motel", "miner", "medal",
  "noble", "nerve", "night", "nurse", "niece", "nifty", "knock", "novel", "notch", "neon",
  "orbit", "older", "olive", "ounce", "opine", "opera", "often", "offer", "outer", "onset",
  "party", "pride", "piano", "power", "place", "probe", "paint", "plain", "pivot", "pluck",
  "quake", "quota", "queen", "quick", "quilt", "quiet", "quirk", "query", "quail", "quell",
  "razor", "river", "rebel", "rally", "rocky", "rinse", "right", "rough", "realm", "relic",
  "solid", "smart", "stone", "sleep", "spark", "sharp", "scout", "spree", "split", "swipe",
  "taste", "trail", "timer", "table", "trick", "tiger", "toxic", "tight", "toast", "thick",
  "unify", "ulcer", "upper", "usual", "upset", "urban", "under", "untie", "utile", "unfit",
  "vivid", "value", "vogue", "vapor", "visit", "venom", "verge", "villa", "vowel", "vault",
  "world", "whine", "wheat", "witch", "watch", "weary", "widen", "wrath", "waver", "woven",
  "xenon", "xerox", "xenia", "xylem", "xysti", "xebec", "xenic", "xeric", "xylic", "xylol",
  "yield", "yacht", "young", "yearn", "yeast", "yodel", "yummy", "yappy", "yawns", "yanks",
  "zebra", "zesty", "zooms", "zoned", "zippy", "zinky", "zappy", "zilch", "zingy", "zloty"
];